# Site settings
title: Andrés Duque
description: 'Business Card Page'
url: ''
baseurl: ''
profilepic: '/images/pic2.jpeg'
bkimage: '/images/matterhorn.jpg'
google_analytics: G-6Y8F3QBCM0
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Andrés Duque'
  email: jandreshduque@gmail.com
  twitter_username: locang0
  github_username:  AndresDuque
  linkedin_username:  jandresduque

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
  
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false


#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
